version: "3.9"
services:
  bookshop_postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/data:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: myRandomPassword
      POSTGRES_USER: book_shop_admin
      POSTGRES_DB: book_shop
  bookshop:
    restart: always
    image: azul/zulu-openjdk-alpine:17-jre
    volumes:
      - ./:/app
    working_dir: /app
    command: java -jar bookshop-1.0.jar --spring.profiles.active=prod
    ports:
      - "8005:8005"
  spring-admin:
    image: ifomkin/bookshopadmin
    restart: always
    ports:
      - "8099:8080"
