server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/book_shop
    username: book_shop_admin
    password: myRandomPassword
  messages:
    basename: lang.messages
  web:
    resources:
      static-locations: classpath:/spring-frontend/
  thymeleaf:
    prefix: classpath:/spring-frontend/
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml
    enabled: false