server:
  port: 8085
  servlet:
    session:
      timeout: 24h
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/book_shop
    username: book_shop_admin
    password: myRandomPassword
  session:
    timeout: ${server.servlet.session.timeout}
    store-type: jdbc
    jdbc:
      #      table-name: session_store
      #      schema: public
      initialize-schema: always
  messages:
    basename: lang.messages
  web:
    resources:
      static-locations: classpath:/spring-frontend/
  thymeleaf:
    prefix: classpath:/spring-frontend/
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml
    enabled: true
bookshop:
  review:
    min-size: 30
  upload:
    path: F:\dev\spring-learn\MyBookShopApp_m3_6\uploads
  download:
    path: F:\dev\spring-learn\MyBookShopApp_m3_6\books